# -*- coding: utf-8 -*-
"""Add common German abbreviations as standalone dictionary entries."""
import json
import sys

sys.stdout.reconfigure(encoding="utf-8")

from pathlib import Path
_SCRIPTS_DIR = Path(__file__).resolve().parent
DICT_PATH = str(_SCRIPTS_DIR.parent / "output" / "dictionary.json")

ABBREVIATIONS = [
    {
        "almanca": "Lkw",
        "artikel": "",
        "turkce": "kamyon, ağır yük taşıtı",
        "kategoriler": ["otomotiv"],
        "aciklama_turkce": "Lastkraftwagen — ağır yük taşımaya yarayan büyük motorlu araç.",
        "ilgili_kayitlar": ["Sattelzug", "Anhänger", "Nutzfahrzeug"],
        "tur": "isim (kısaltma)",
        "ornek_almanca": "Der Lkw transportiert Waren von der Fabrik zum Lager.",
        "ornek_turkce": "Kamyon, malları fabrikadan depoya taşır.",
        "ornekler": [
            {"almanca": "Der Lkw transportiert Waren von der Fabrik zum Lager.", "turkce": "Kamyon, malları fabrikadan depoya taşır."},
            {"almanca": "Lkw-Fahrer müssen einen speziellen Führerschein haben.", "turkce": "Kamyon sürücülerinin özel ehliyet alması gerekir."},
        ],
        "kaynak": "özel — standart Almanca kısaltma",
        "kaynak_url": "",
        "ceviri_durumu": "doğrulanmış",
        "ceviri_inceleme_notu": "",
        "ceviri_kaynaklari": [],
        "not": "Lastkraftwagen kısaltması. Ayrıca LKW (büyük harf) olarak da yazılır.",
        "referans_linkler": {
            "duden": "https://www.duden.de/suchen/dudenonline/Lkw",
            "dwds": "https://www.dwds.de/wb/Lkw",
            "wiktionary_de": "https://de.wiktionary.org/wiki/Lkw",
        },
        "seviye": "A2",
        "genitiv_endung": "",
        "kelime_ailesi": ["Lastkraftwagen", "Lkw-Fahrer", "Sattelzug"],
    },
    {
        "almanca": "LKW",
        "artikel": "",
        "turkce": "kamyon, ağır yük taşıtı",
        "kategoriler": ["otomotiv"],
        "aciklama_turkce": "Lastkraftwagen kısaltması (büyük harf yazımı). Lkw ile aynı anlama gelir.",
        "ilgili_kayitlar": ["Lkw", "Sattelzug", "Nutzfahrzeug"],
        "tur": "isim (kısaltma)",
        "ornek_almanca": "Ein LKW mit Anhänger darf nicht in die Innenstadt fahren.",
        "ornek_turkce": "Römorklu bir kamyon şehir merkezine giremez.",
        "ornekler": [
            {"almanca": "Ein LKW mit Anhänger darf nicht in die Innenstadt fahren.", "turkce": "Römorklu bir kamyon şehir merkezine giremez."},
        ],
        "kaynak": "özel — standart Almanca kısaltma",
        "kaynak_url": "",
        "ceviri_durumu": "doğrulanmış",
        "ceviri_inceleme_notu": "",
        "ceviri_kaynaklari": [],
        "not": "Lastkraftwagen kısaltması. Ayrıca Lkw (küçük harf) olarak da yazılır.",
        "referans_linkler": {
            "duden": "https://www.duden.de/suchen/dudenonline/Lkw",
            "dwds": "https://www.dwds.de/wb/Lkw",
            "wiktionary_de": "https://de.wiktionary.org/wiki/Lkw",
        },
        "seviye": "A2",
        "genitiv_endung": "",
        "kelime_ailesi": ["Lastkraftwagen", "Lkw-Fahrer", "Sattelzug"],
    },
    {
        "almanca": "Pkw",
        "artikel": "der",
        "turkce": "otomobil, binek araç",
        "kategoriler": ["otomotiv"],
        "aciklama_turkce": "Personenkraftwagen kısaltması — yolcu taşımaya yarayan motorlu taşıt.",
        "ilgili_kayitlar": ["Fahrzeug", "Kraftfahrzeug", "Auto"],
        "tur": "isim (kısaltma)",
        "ornek_almanca": "Der Pkw steht in der Garage und ist fahrbereit.",
        "ornek_turkce": "Otomobil garajda duruyor ve sürüşe hazır.",
        "ornekler": [
            {"almanca": "Der Pkw steht in der Garage und ist fahrbereit.", "turkce": "Otomobil garajda duruyor ve sürüşe hazır."},
            {"almanca": "Pkw-Fahrer müssen die Verkehrsregeln beachten.", "turkce": "Otomobil sürücüleri trafik kurallarına uymak zorundadır."},
        ],
        "kaynak": "özel — standart Almanca kısaltma",
        "kaynak_url": "",
        "ceviri_durumu": "doğrulanmış",
        "ceviri_inceleme_notu": "",
        "ceviri_kaynaklari": [],
        "not": "Personenkraftwagen kısaltması. PKW (büyük harf) olarak da yazılır.",
        "referans_linkler": {
            "duden": "https://www.duden.de/suchen/dudenonline/Pkw",
            "dwds": "https://www.dwds.de/wb/Pkw",
            "wiktionary_de": "https://de.wiktionary.org/wiki/Pkw",
        },
        "seviye": "A2",
        "genitiv_endung": "s",
        "kelime_ailesi": ["Personenkraftwagen", "Pkw-Fahrer", "Fahrzeug"],
    },
    {
        "almanca": "PKW",
        "artikel": "der",
        "turkce": "otomobil, binek araç",
        "kategoriler": ["otomotiv"],
        "aciklama_turkce": "Personenkraftwagen kısaltması (büyük harf yazımı). Pkw ile aynı anlama gelir.",
        "ilgili_kayitlar": ["Pkw", "Fahrzeug", "Auto"],
        "tur": "isim (kısaltma)",
        "ornek_almanca": "Der PKW wird beim TÜV angemeldet.",
        "ornek_turkce": "Otomobil TÜV'e kayıt yaptırılır.",
        "ornekler": [
            {"almanca": "Der PKW wird beim TÜV angemeldet.", "turkce": "Otomobil TÜV'e kayıt yaptırılır."},
        ],
        "kaynak": "özel — standart Almanca kısaltma",
        "kaynak_url": "",
        "ceviri_durumu": "doğrulanmış",
        "ceviri_inceleme_notu": "",
        "ceviri_kaynaklari": [],
        "not": "Personenkraftwagen kısaltması. Pkw (karışık harf) olarak da yazılır.",
        "referans_linkler": {
            "duden": "https://www.duden.de/suchen/dudenonline/Pkw",
            "dwds": "https://www.dwds.de/wb/Pkw",
            "wiktionary_de": "https://de.wiktionary.org/wiki/Pkw",
        },
        "seviye": "A2",
        "genitiv_endung": "s",
        "kelime_ailesi": ["Personenkraftwagen", "Pkw-Fahrer", "Fahrzeug"],
    },
    {
        "almanca": "Kfz",
        "artikel": "das",
        "turkce": "motorlu taşıt, araç",
        "kategoriler": ["otomotiv"],
        "aciklama_turkce": "Kraftfahrzeug kısaltması — motor gücüyle çalışan her türlü taşıt.",
        "ilgili_kayitlar": ["Kraftfahrzeug", "Fahrzeug", "Pkw", "Lkw"],
        "tur": "isim (kısaltma)",
        "ornek_almanca": "Das Kfz-Kennzeichen gibt Auskunft über den Zulassungsbezirk.",
        "ornek_turkce": "Araç plakası tescil bölgesi hakkında bilgi verir.",
        "ornekler": [
            {"almanca": "Das Kfz-Kennzeichen gibt Auskunft über den Zulassungsbezirk.", "turkce": "Araç plakası tescil bölgesi hakkında bilgi verir."},
            {"almanca": "Der Kfz-Mechaniker repariert das Fahrzeug in der Werkstatt.", "turkce": "Araç tamircisi aracı atölyede tamir eder."},
        ],
        "kaynak": "özel — standart Almanca kısaltma",
        "kaynak_url": "",
        "ceviri_durumu": "doğrulanmış",
        "ceviri_inceleme_notu": "",
        "ceviri_kaynaklari": [],
        "not": "Kraftfahrzeug kısaltması. KFZ (büyük harf) ve Kfz (karışık harf) olarak yazılır.",
        "referans_linkler": {
            "duden": "https://www.duden.de/suchen/dudenonline/Kfz",
            "dwds": "https://www.dwds.de/wb/Kfz",
            "wiktionary_de": "https://de.wiktionary.org/wiki/Kfz",
        },
        "seviye": "B1",
        "genitiv_endung": "s",
        "kelime_ailesi": ["Kraftfahrzeug", "Kfz-Mechaniker", "Kfz-Kennzeichen", "Kfz-Steuer"],
    },
    {
        "almanca": "KFZ",
        "artikel": "das",
        "turkce": "motorlu taşıt, araç",
        "kategoriler": ["otomotiv"],
        "aciklama_turkce": "Kraftfahrzeug kısaltması (büyük harf yazımı). Kfz ile aynı anlama gelir.",
        "ilgili_kayitlar": ["Kfz", "Kraftfahrzeug", "Fahrzeug"],
        "tur": "isim (kısaltma)",
        "ornek_almanca": "Das KFZ muss jährlich zur Hauptuntersuchung.",
        "ornek_turkce": "Araç her yıl periyodik muayeneye gitmek zorundadır.",
        "ornekler": [
            {"almanca": "Das KFZ muss jährlich zur Hauptuntersuchung.", "turkce": "Araç her yıl periyodik muayeneye gitmek zorundadır."},
        ],
        "kaynak": "özel — standart Almanca kısaltma",
        "kaynak_url": "",
        "ceviri_durumu": "doğrulanmış",
        "ceviri_inceleme_notu": "",
        "ceviri_kaynaklari": [],
        "not": "Kraftfahrzeug kısaltması. Kfz (karışık harf) olarak da yazılır.",
        "referans_linkler": {
            "duden": "https://www.duden.de/suchen/dudenonline/Kfz",
            "dwds": "https://www.dwds.de/wb/Kfz",
            "wiktionary_de": "https://de.wiktionary.org/wiki/Kfz",
        },
        "seviye": "B1",
        "genitiv_endung": "s",
        "kelime_ailesi": ["Kraftfahrzeug", "Kfz-Mechaniker", "Kfz-Kennzeichen"],
    },
    {
        "almanca": "TÜV",
        "artikel": "der",
        "turkce": "araç muayene kuruluşu, teknik muayene",
        "kategoriler": ["otomotiv"],
        "aciklama_turkce": "Technischer Überwachungsverein kısaltması — araçların ve teknik sistemlerin güvenliğini denetleyen Alman kuruluşu.",
        "ilgili_kayitlar": ["Hauptuntersuchung", "Fahrzeugprüfung", "DEKRA"],
        "tur": "isim (kısaltma)",
        "ornek_almanca": "Mein Auto muss zum TÜV, weil die Hauptuntersuchung fällig ist.",
        "ornek_turkce": "Arabam periyodik muayenesi dolduğu için TÜV'e gitmesi gerekiyor.",
        "ornekler": [
            {"almanca": "Mein Auto muss zum TÜV, weil die Hauptuntersuchung fällig ist.", "turkce": "Arabam periyodik muayenesi dolduğu için TÜV'e gitmesi gerekiyor."},
            {"almanca": "Das Fahrzeug hat den TÜV nicht bestanden.", "turkce": "Araç TÜV muayenesini geçemedi."},
        ],
        "kaynak": "özel — standart Almanca kısaltma",
        "kaynak_url": "",
        "ceviri_durumu": "doğrulanmış",
        "ceviri_inceleme_notu": "",
        "ceviri_kaynaklari": [],
        "not": "Technischer Überwachungsverein. Araç muayenesi için 'zum TÜV fahren' veya 'den TÜV machen' deyimleri kullanılır.",
        "referans_linkler": {
            "duden": "https://www.duden.de/suchen/dudenonline/TUeV",
            "dwds": "https://www.dwds.de/wb/TÜV",
            "wiktionary_de": "https://de.wiktionary.org/wiki/TÜV",
        },
        "seviye": "A2",
        "genitiv_endung": "s",
        "kelime_ailesi": ["Hauptuntersuchung", "TÜV-Plakette", "TÜV-Prüfung"],
    },
    {
        "almanca": "ADAC",
        "artikel": "der",
        "turkce": "Alman Otomobil Kulübü",
        "kategoriler": ["otomotiv"],
        "aciklama_turkce": "Allgemeiner Deutscher Automobil-Club kısaltması — Almanya'nın en büyük otomobil kulübü ve yol yardım kuruluşu.",
        "ilgili_kayitlar": ["Pannenhilfe", "Fahrzeugversicherung"],
        "tur": "isim (kısaltma)",
        "ornek_almanca": "Der ADAC leistet bei Pannen schnelle Hilfe auf der Autobahn.",
        "ornek_turkce": "ADAC, otoyoldaki arızalarda hızlı yardım sağlar.",
        "ornekler": [
            {"almanca": "Der ADAC leistet bei Pannen schnelle Hilfe auf der Autobahn.", "turkce": "ADAC, otoyoldaki arızalarda hızlı yardım sağlar."},
            {"almanca": "Ich bin ADAC-Mitglied und erhalte Pannenhilfe.", "turkce": "ADAC üyesiyim ve arıza yardımı alıyorum."},
        ],
        "kaynak": "özel — standart Almanca kısaltma",
        "kaynak_url": "",
        "ceviri_durumu": "doğrulanmış",
        "ceviri_inceleme_notu": "",
        "ceviri_kaynaklari": [],
        "not": "Allgemeiner Deutscher Automobil-Club. Almanya'nın en büyük otomobil derneğidir.",
        "referans_linkler": {
            "duden": "https://www.duden.de/suchen/dudenonline/ADAC",
            "wiktionary_de": "https://de.wiktionary.org/wiki/ADAC",
        },
        "seviye": "B1",
        "genitiv_endung": "s",
        "kelime_ailesi": ["Pannenhilfe", "Automobil-Club"],
    },
    {
        "almanca": "HU",
        "artikel": "die",
        "turkce": "periyodik araç muayenesi",
        "kategoriler": ["otomotiv"],
        "aciklama_turkce": "Hauptuntersuchung kısaltması — araçların belirli aralıklarla yaptırması zorunlu teknik güvenlik muayenesi.",
        "ilgili_kayitlar": ["TÜV", "Hauptuntersuchung", "DEKRA"],
        "tur": "isim (kısaltma)",
        "ornek_almanca": "Die HU ist alle zwei Jahre Pflicht für Pkw.",
        "ornek_turkce": "Periyodik araç muayenesi binek araçlar için iki yılda bir zorunludur.",
        "ornekler": [
            {"almanca": "Die HU ist alle zwei Jahre Pflicht für Pkw.", "turkce": "Periyodik araç muayenesi binek araçlar için iki yılda bir zorunludur."},
        ],
        "kaynak": "özel — standart Almanca kısaltma",
        "kaynak_url": "",
        "ceviri_durumu": "doğrulanmış",
        "ceviri_inceleme_notu": "",
        "ceviri_kaynaklari": [],
        "not": "Hauptuntersuchung kısaltması. TÜV ile eş anlamlı olarak kullanılır.",
        "referans_linkler": {
            "duden": "https://www.duden.de/suchen/dudenonline/HU",
            "wiktionary_de": "https://de.wiktionary.org/wiki/Hauptuntersuchung",
        },
        "seviye": "B1",
        "genitiv_endung": "",
        "kelime_ailesi": ["TÜV", "Hauptuntersuchung", "Fahrzeugprüfung"],
    },
    {
        "almanca": "PS",
        "artikel": "die",
        "turkce": "beygir gücü",
        "kategoriler": ["otomotiv"],
        "aciklama_turkce": "Pferdestärke kısaltması — motorun güç birimi. 1 PS = 0,7355 kW.",
        "ilgili_kayitlar": ["kW", "Motorleistung", "Hubraum"],
        "tur": "birim (kısaltma)",
        "ornek_almanca": "Das Fahrzeug hat einen Motor mit 150 PS.",
        "ornek_turkce": "150 beygir gücünde motoru olan bir araç.",
        "ornekler": [
            {"almanca": "Das Fahrzeug hat einen Motor mit 150 PS.", "turkce": "150 beygir gücünde motoru olan bir araç."},
            {"almanca": "Wie viel PS hat dein Auto?", "turkce": "Araban kaç beygir gücünde?"},
        ],
        "kaynak": "özel — standart birim kısaltması",
        "kaynak_url": "",
        "ceviri_durumu": "doğrulanmış",
        "ceviri_inceleme_notu": "",
        "ceviri_kaynaklari": [],
        "not": "Pferdestärke. 1 PS = 0,7355 kW. Resmi standart birim kW'dır ancak PS günlük kullanımda yaygındır.",
        "referans_linkler": {
            "duden": "https://www.duden.de/suchen/dudenonline/PS",
            "dwds": "https://www.dwds.de/wb/Pferdestärke",
            "wiktionary_de": "https://de.wiktionary.org/wiki/PS",
        },
        "seviye": "A2",
        "genitiv_endung": "",
        "kelime_ailesi": ["kW", "Motorleistung", "Pferdestärke"],
    },
    {
        "almanca": "kW",
        "artikel": "das",
        "turkce": "kilovat, kW",
        "kategoriler": ["otomotiv", "genel"],
        "aciklama_turkce": "Kilowatt kısaltması — güç birimi. Araç motorlarının resmi güç birimi. 1 kW = 1,36 PS.",
        "ilgili_kayitlar": ["PS", "Motorleistung", "Watt"],
        "tur": "birim (kısaltma)",
        "ornek_almanca": "Der Motor leistet 110 kW, was etwa 150 PS entspricht.",
        "ornek_turkce": "Motor 110 kW güç üretiyor, bu yaklaşık 150 PS'e karşılık gelir.",
        "ornekler": [
            {"almanca": "Der Motor leistet 110 kW, was etwa 150 PS entspricht.", "turkce": "Motor 110 kW güç üretiyor, bu yaklaşık 150 PS'e karşılık gelir."},
        ],
        "kaynak": "özel — standart birim kısaltması",
        "kaynak_url": "",
        "ceviri_durumu": "doğrulanmış",
        "ceviri_inceleme_notu": "",
        "ceviri_kaynaklari": [],
        "not": "Kilowatt. Araçlar için resmi güç birimi. 1 kW ~= 1,36 PS.",
        "referans_linkler": {
            "wiktionary_de": "https://de.wiktionary.org/wiki/Kilowatt",
        },
        "seviye": "A2",
        "genitiv_endung": "s",
        "kelime_ailesi": ["Watt", "PS", "Motorleistung"],
    },
    {
        "almanca": "Nm",
        "artikel": "das",
        "turkce": "Newton metre, tork birimi",
        "kategoriler": ["otomotiv"],
        "aciklama_turkce": "Newtonmeter kısaltması — tork (döndürme momenti) birimi. Motor özelliklerinde kullanılır.",
        "ilgili_kayitlar": ["Drehmoment", "PS", "kW"],
        "tur": "birim (kısaltma)",
        "ornek_almanca": "Das maximale Drehmoment beträgt 350 Nm.",
        "ornek_turkce": "Maksimum tork 350 Nm'dir.",
        "ornekler": [
            {"almanca": "Das maximale Drehmoment beträgt 350 Nm.", "turkce": "Maksimum tork 350 Nm'dir."},
        ],
        "kaynak": "özel — standart birim kısaltması",
        "kaynak_url": "",
        "ceviri_durumu": "doğrulanmış",
        "ceviri_inceleme_notu": "",
        "ceviri_kaynaklari": [],
        "not": "Newtonmeter — tork birimi. Araç teknik özelliklerinde sıkça geçer.",
        "referans_linkler": {
            "wiktionary_de": "https://de.wiktionary.org/wiki/Newtonmeter",
        },
        "seviye": "B2",
        "genitiv_endung": "s",
        "kelime_ailesi": ["Drehmoment", "kW", "PS"],
    },
    {
        "almanca": "km/h",
        "artikel": "",
        "turkce": "km/s, kilometre/saat",
        "kategoriler": ["otomotiv", "genel"],
        "aciklama_turkce": "Kilometre pro Stunde — hız birimi.",
        "ilgili_kayitlar": ["Geschwindigkeit", "Tempo", "Tacho"],
        "tur": "birim (kısaltma)",
        "ornek_almanca": "Die Höchstgeschwindigkeit auf der Autobahn beträgt 130 km/h.",
        "ornek_turkce": "Otoyoldaki azami hız 130 km/s'dir.",
        "ornekler": [
            {"almanca": "Die Höchstgeschwindigkeit auf der Autobahn beträgt 130 km/h.", "turkce": "Otoyoldaki azami hız 130 km/s'dir."},
            {"almanca": "Das Auto fährt mit 100 km/h.", "turkce": "Araba saatte 100 km hızla gidiyor."},
        ],
        "kaynak": "özel — standart birim kısaltması",
        "kaynak_url": "",
        "ceviri_durumu": "doğrulanmış",
        "ceviri_inceleme_notu": "",
        "ceviri_kaynaklari": [],
        "not": "Kilometre pro Stunde. Evrensel hız birimi.",
        "referans_linkler": {
            "wiktionary_de": "https://de.wiktionary.org/wiki/km/h",
        },
        "seviye": "A1",
        "genitiv_endung": "",
        "kelime_ailesi": ["Geschwindigkeit", "m/s", "mph"],
    },
    {
        "almanca": "OBD",
        "artikel": "das",
        "turkce": "araç tanı sistemi, OBD",
        "kategoriler": ["otomotiv"],
        "aciklama_turkce": "On-Board-Diagnose kısaltması — araçtaki elektronik kontrol ünitelerini izleyen ve arıza kodlarını saklayan yerleşik tanı sistemi.",
        "ilgili_kayitlar": ["Fehlerspeicher", "Motorsteuergerät", "Diagnosegerät"],
        "tur": "isim (kısaltma)",
        "ornek_almanca": "Das OBD-Gerät liest die Fehlercodes aus dem Steuergerät aus.",
        "ornek_turkce": "OBD cihazı, kontrol ünitesindeki arıza kodlarını okur.",
        "ornekler": [
            {"almanca": "Das OBD-Gerät liest die Fehlercodes aus dem Steuergerät aus.", "turkce": "OBD cihazı, kontrol ünitesindeki arıza kodlarını okur."},
            {"almanca": "Über die OBD-Schnittstelle kann man Fahrzeugdaten auslesen.", "turkce": "OBD arayüzü üzerinden araç verileri okunabilir."},
        ],
        "kaynak": "özel — standart Almanca kısaltma",
        "kaynak_url": "",
        "ceviri_durumu": "doğrulanmış",
        "ceviri_inceleme_notu": "",
        "ceviri_kaynaklari": [],
        "not": "On-Board-Diagnose. OBD-II standardı 1996'dan beri zorunludur.",
        "referans_linkler": {
            "wiktionary_de": "https://de.wiktionary.org/wiki/On-Board-Diagnose",
        },
        "seviye": "C1",
        "genitiv_endung": "s",
        "kelime_ailesi": ["Fehlerspeicher", "Diagnosegerät", "Motorsteuergerät"],
    },
    {
        "almanca": "GmbH",
        "artikel": "die",
        "turkce": "limited şirket",
        "kategoriler": ["genel", "ticaret"],
        "aciklama_turkce": "Gesellschaft mit beschränkter Haftung kısaltması — sınırlı sorumluluklu şirket. Türkiye'deki Ltd. Şti. ile eşdeğerdir.",
        "ilgili_kayitlar": ["AG", "Unternehmen", "Firma"],
        "tur": "isim (kısaltma)",
        "ornek_almanca": "Die Firma Müller GmbH hat ihren Sitz in Berlin.",
        "ornek_turkce": "Müller GmbH şirketinin merkezi Berlin'dedir.",
        "ornekler": [
            {"almanca": "Die Firma Müller GmbH hat ihren Sitz in Berlin.", "turkce": "Müller GmbH şirketinin merkezi Berlin'dedir."},
        ],
        "kaynak": "özel — standart Almanca kısaltma",
        "kaynak_url": "",
        "ceviri_durumu": "doğrulanmış",
        "ceviri_inceleme_notu": "",
        "ceviri_kaynaklari": [],
        "not": "Gesellschaft mit beschränkter Haftung. Almanya'nın en yaygın şirket türüdür.",
        "referans_linkler": {
            "duden": "https://www.duden.de/suchen/dudenonline/GmbH",
            "dwds": "https://www.dwds.de/wb/GmbH",
            "wiktionary_de": "https://de.wiktionary.org/wiki/GmbH",
        },
        "seviye": "B2",
        "genitiv_endung": "",
        "kelime_ailesi": ["AG", "Unternehmen", "Kapitalgesellschaft"],
    },
    {
        "almanca": "AG",
        "artikel": "die",
        "turkce": "anonim şirket",
        "kategoriler": ["genel", "ticaret"],
        "aciklama_turkce": "Aktiengesellschaft kısaltması — hisse senetleri borsada işlem görebilen büyük sermaye şirketi.",
        "ilgili_kayitlar": ["GmbH", "Unternehmen", "Aktie"],
        "tur": "isim (kısaltma)",
        "ornek_almanca": "Die Volkswagen AG hat Werke in vielen Ländern.",
        "ornek_turkce": "Volkswagen AG'nin birçok ülkede fabrikası vardır.",
        "ornekler": [
            {"almanca": "Die Volkswagen AG hat Werke in vielen Ländern.", "turkce": "Volkswagen AG'nin birçok ülkede fabrikası vardır."},
        ],
        "kaynak": "özel — standart Almanca kısaltma",
        "kaynak_url": "",
        "ceviri_durumu": "doğrulanmış",
        "ceviri_inceleme_notu": "",
        "ceviri_kaynaklari": [],
        "not": "Aktiengesellschaft kısaltması.",
        "referans_linkler": {
            "duden": "https://www.duden.de/suchen/dudenonline/AG",
            "dwds": "https://www.dwds.de/wb/AG",
            "wiktionary_de": "https://de.wiktionary.org/wiki/AG",
        },
        "seviye": "B2",
        "genitiv_endung": "",
        "kelime_ailesi": ["GmbH", "Aktie", "Börse"],
    },
    {
        "almanca": "MwSt",
        "artikel": "die",
        "turkce": "KDV, katma değer vergisi",
        "kategoriler": ["genel"],
        "aciklama_turkce": "Mehrwertsteuer kısaltması — mal ve hizmetler üzerinden alınan tüketim vergisi.",
        "ilgili_kayitlar": ["Steuer", "Mehrwertsteuer"],
        "tur": "isim (kısaltma)",
        "ornek_almanca": "Der Preis beträgt 119 Euro inklusive MwSt.",
        "ornek_turkce": "Fiyat KDV dahil 119 Avro'dur.",
        "ornekler": [
            {"almanca": "Der Preis beträgt 119 Euro inklusive MwSt.", "turkce": "Fiyat KDV dahil 119 Avro'dur."},
            {"almanca": "Die MwSt in Deutschland beträgt 19 Prozent.", "turkce": "Almanya'da KDV yüzde 19'dur."},
        ],
        "kaynak": "özel — standart Almanca kısaltma",
        "kaynak_url": "",
        "ceviri_durumu": "doğrulanmış",
        "ceviri_inceleme_notu": "",
        "ceviri_kaynaklari": [],
        "not": "Mehrwertsteuer kısaltması. MWSt olarak da yazılır.",
        "referans_linkler": {
            "duden": "https://www.duden.de/suchen/dudenonline/MwSt",
            "dwds": "https://www.dwds.de/wb/Mehrwertsteuer",
            "wiktionary_de": "https://de.wiktionary.org/wiki/Mehrwertsteuer",
        },
        "seviye": "B1",
        "genitiv_endung": "",
        "kelime_ailesi": ["Mehrwertsteuer", "Steuer", "Umsatzsteuer"],
    },
    {
        "almanca": "z.B.",
        "artikel": "",
        "turkce": "örneğin, mesela",
        "kategoriler": ["genel"],
        "aciklama_turkce": "zum Beispiel kısaltması — örnek vermek için kullanılan standart Almanca kısaltma.",
        "ilgili_kayitlar": ["u.a.", "d.h.", "usw."],
        "tur": "zarf (kısaltma)",
        "ornek_almanca": "Es gibt viele Möglichkeiten, z.B. mit dem Zug oder dem Auto zu reisen.",
        "ornek_turkce": "Örneğin tren veya arabayla seyahat etmek gibi birçok olasılık vardır.",
        "ornekler": [
            {"almanca": "Es gibt viele Möglichkeiten, z.B. mit dem Zug oder dem Auto zu reisen.", "turkce": "Örneğin tren veya arabayla seyahat etmek gibi birçok olasılık vardır."},
        ],
        "kaynak": "özel — standart Almanca kısaltma",
        "kaynak_url": "",
        "ceviri_durumu": "doğrulanmış",
        "ceviri_inceleme_notu": "",
        "ceviri_kaynaklari": [],
        "not": "zum Beispiel. Çok yaygın kullanılan kısaltma.",
        "referans_linkler": {
            "duden": "https://www.duden.de/suchen/dudenonline/Beispiel",
        },
        "seviye": "A1",
        "genitiv_endung": "",
        "kelime_ailesi": ["Beispiel", "u.a.", "d.h."],
    },
    {
        "almanca": "d.h.",
        "artikel": "",
        "turkce": "yani, demek ki",
        "kategoriler": ["genel"],
        "aciklama_turkce": "das heißt kısaltması — açıklama yapmak için kullanılır.",
        "ilgili_kayitlar": ["z.B.", "usw.", "u.a."],
        "tur": "zarf (kısaltma)",
        "ornek_almanca": "Das Geschäft ist heute geschlossen, d.h. wir müssen morgen kommen.",
        "ornek_turkce": "Dükkan bugün kapalı, yani yarın gelmemiz gerekiyor.",
        "ornekler": [
            {"almanca": "Das Geschäft ist heute geschlossen, d.h. wir müssen morgen kommen.", "turkce": "Dükkan bugün kapalı, yani yarın gelmemiz gerekiyor."},
        ],
        "kaynak": "özel — standart Almanca kısaltma",
        "kaynak_url": "",
        "ceviri_durumu": "doğrulanmış",
        "ceviri_inceleme_notu": "",
        "ceviri_kaynaklari": [],
        "not": "das heißt. Çok yaygın kullanılan kısaltma.",
        "referans_linkler": {
            "duden": "https://www.duden.de/suchen/dudenonline/heissen",
        },
        "seviye": "A2",
        "genitiv_endung": "",
        "kelime_ailesi": ["das heißt", "z.B.", "usw."],
    },
    {
        "almanca": "usw.",
        "artikel": "",
        "turkce": "ve benzeri, vb.",
        "kategoriler": ["genel"],
        "aciklama_turkce": "und so weiter kısaltması — liste sonunda 've benzerleri' anlamında kullanılır.",
        "ilgili_kayitlar": ["z.B.", "d.h.", "u.a."],
        "tur": "zarf (kısaltma)",
        "ornek_almanca": "Wir brauchen Werkzeug, Schrauben, Muttern usw.",
        "ornek_turkce": "Alet, vida, somun vb. malzemelere ihtiyacımız var.",
        "ornekler": [
            {"almanca": "Wir brauchen Werkzeug, Schrauben, Muttern usw.", "turkce": "Alet, vida, somun vb. malzemelere ihtiyacımız var."},
        ],
        "kaynak": "özel — standart Almanca kısaltma",
        "kaynak_url": "",
        "ceviri_durumu": "doğrulanmış",
        "ceviri_inceleme_notu": "",
        "ceviri_kaynaklari": [],
        "not": "und so weiter. Yaygın kullanılan kısaltma.",
        "referans_linkler": {
            "duden": "https://www.duden.de/suchen/dudenonline/weiter",
        },
        "seviye": "A1",
        "genitiv_endung": "",
        "kelime_ailesi": ["z.B.", "d.h.", "etc."],
    },
    {
        "almanca": "Std.",
        "artikel": "die",
        "turkce": "saat (zaman birimi)",
        "kategoriler": ["genel"],
        "aciklama_turkce": "Stunde kısaltması — resmi yazışmalarda ve tablolarda kullanılır.",
        "ilgili_kayitlar": ["Stunde", "Min.", "Sek."],
        "tur": "isim (kısaltma)",
        "ornek_almanca": "Die Fahrt dauert ca. 2 Std.",
        "ornek_turkce": "Yolculuk yaklaşık 2 saat sürer.",
        "ornekler": [
            {"almanca": "Die Fahrt dauert ca. 2 Std.", "turkce": "Yolculuk yaklaşık 2 saat sürer."},
        ],
        "kaynak": "özel — standart Almanca kısaltma",
        "kaynak_url": "",
        "ceviri_durumu": "doğrulanmış",
        "ceviri_inceleme_notu": "",
        "ceviri_kaynaklari": [],
        "not": "Stunde kısaltması. Çoğul: Std. veya Stdn.",
        "referans_linkler": {
            "duden": "https://www.duden.de/suchen/dudenonline/Stunde",
        },
        "seviye": "A1",
        "genitiv_endung": "",
        "kelime_ailesi": ["Stunde", "Minute", "Sekunde"],
    },
]


def main():
    with open(DICT_PATH, encoding="utf-8") as f:
        data = json.load(f)

    existing_keys = {r.get("almanca", "").lower() for r in data}

    new_entries = []
    for entry in ABBREVIATIONS:
        key = entry["almanca"].lower()
        if key not in existing_keys:
            new_entries.append(entry)
            existing_keys.add(key)

    print(f"Adding {len(new_entries)} new abbreviation entries:")
    for e in new_entries:
        print(f"  + {e['almanca']} -> {e['turkce'][:45]}")

    data.extend(new_entries)

    with open(DICT_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"\nDone. Total records: {len(data)}")


if __name__ == "__main__":
    main()
